### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Ultrawipf** [samphonic/MoppyClassic#8] opened 2012-04-22 15:11 UTC
First it would be nice to set the highest/lowest notes for each/all drive in the interface.
Second: support for more channels (with arduino mega).
Third: i need to reconnect in the interface or reset the arduino to play a new track?! otherwise the arduino recieves data but nothing happens.

**Comment by samphonic** [comment] 2012-04-24 22:00
First: An interesting idea, though generally there's no reason to include notes above a certain range at all since the drives just can't play them at all.  I suppose if you were using the same interface to connect to a non-floppy-drive step motor though this might be useful.

Second: I'm hesitant to just add more channels to the Arduino code in-case people want to use the other PINs on the Arduino for something, but maybe that's not really a concern.  The Java code already supports the maximum number of MIDI channels (16), so all that needs to change is the Arduino code.

Third: You probably shouldn't need to do that (it's not a problem for me), so that's probably a bug.

**Comment by Ultrawipf** [comment] 2012-04-25 08:46
hmm so i can just expand the arduino code like in your example to get 16 channels?
my problem is that some of my drives just cant play the highest notes, but others can. so it would be nice to set the limits in the interface. But i have no idea how to write in java ;)

The problem with the reconnect: i updated the code an recompiled it but it got even worse... the first time i just had to push reset but now i need to reconnect.
If you updated the code i will download the newest version and try again...

**Comment by samphonic** [comment] 2012-04-25 21:03
You can indeed expand the Arduino code up to 16 channels without much issue (make sure you expand the arrays in the Arduino code as well).

I'm not saying no to an in-interface limit, but since the end goal would be to play all the written notes somehow (you don't just want to cut out chunks of music in a certain range), the music should probably be assigned to channels that can handle it, rather than cutting the notes out after the fact.  In other words, it's probably better to just arrange music that your drives can actually play, rather than have the software not play all of your music.

I haven't changed the code relating to your connecting issue, but I've never had that problem either.  I don't know for sure since I can't reproduce it, but it does sound a lot like COM drive issues.  Maybe double-check that rxtxcomm is installed and happy, or try a different built of it from another site?

**Comment by Ultrawipf** [comment] 2012-04-29 11:49
Today i got the code working on an arduino mega 2560 with all 16 channels but the reset problem still appears.
The arduino keeps looping the resetAll function if it recieves the "100" reset message from the interface when i click on the reset button. it seem that the serial.Flush() doesnt work since i used arduino compiler version 1.0.
on the arduino site they said: "Flush: Waits for the transmission of outgoing serial data to complete. (Prior to Arduino 1.0, this instead removed any buffered incoming serial data.)"

**Comment by knorke74** [comment] 2012-05-01 14:48
In Arduino 1.0 you have to replace Serial.flush() with something like

```
while(Serial.available() > 0){
        Serial.read();
      }
```

Works fine for me now.

**Comment by Ultrawipf** [comment] 2012-05-03 19:53
ohh thanks
works great and solved my reconnect problem :)

**Comment by samphonic** [comment] 2012-05-04 08:34
Thanks again knorke74, I just updated the code so that that's fixed.  Great catch.

Ultrawipf, I can't wait to see a video of 16 channels in action; that sounds amazing!

**Closed as completed by samphonic** 2012-05-04 08:34 UTC
