### ISSUE TITLE
Help Request - Can't determine if this is a software or hardware issue

### ISSUE THREAD

**Issue by ten0rplaya04** [samphonic/MoppyClassic#75] opened 2014-07-20 00:43 UTC
I've been trying to get this working for a few days now so it's time I ask for some help.

Setup:
Windows 7/Netbeans/Moppy Advanced
Arduino Uno
2x Panasonic Floppy Drives (3.5in)
Both cables are jumped on pins 14/13 (12/11 did not light up drive)
Green Wire on Pin 18 (Plugged into pins 3 and 5)
Blue Wire on Pin 20 (Plugged into pins 2 and 4)
Pins 17 & 21 are plugged into bread board with common ground to arduino
Tetris sample midi

Problem: Drive stepper moves, but less than a quarter inch.  No "music" can be heard from drives.

Troubleshooting:
- Verified ground pins are on side with "nub"
- Verified Arduino is transmitting to drives (light blinks and drives click along)
- Reversed step and direction pins
  ------No effect, drive continues to step back and forth
- Tested with only one drive connected (changing between each drive independantly)
- Tested different channels, starting with 1 & 2, then 2 & 3, and finally 3 & 4 moving the drives each time.
  ------Drives change their clicking, but no other movement
- Netbeans does not have any error messages

**Comment by ten0rplaya04** [comment] 2014-07-20 12:32
Update: I'm guessing it's hardware because I found a Youtube video that showed someone testing a floppy drive by using hard drive/cd drive jumpers.  I plugged in the jumpers on pins 11/12 and 17/18 directly on the drive.  Attempted to trip 19/20 and the drive just clicks. 

Anyone know anything special about these Panasonic (HP computer) floppy drives that I might be missing? N31K Stepper

**Comment by tg44** [comment] 2014-07-20 14:05
Hy!

Did you tryed this: https://www.youtube.com/watch?v=w6tuMn5sPyM ?
If you do it well, the driver led is always on (there need a jumper). Im not good with pins and numbers, but this video helped me troubleshooting the drivers.

Oh and I forgot a thing, you must take all the grounds to the same level as arduino ground. That coud do a lot off problem, but try the drivers in the manual way first.

**Comment by ten0rplaya04** [comment] 2014-07-20 15:58
Thanks for the reply.

I followed Sams video the first time around.  When my drives just started clicking during play, I was desperately searching for videos to find floppy drive issues.  The video I found is this one https://www.youtube.com/watch?v=z58MdRGgEOQ and I used jumpers to get the green light on the drive, and connect/disconnect the direction pin.  I tried tripping the step pin with a screwdriver and the drive clicks, but doesn't move forward like in the video I've linked.  The drive clicks forward a few clicks and then clicks backwards a few.

**Comment by samphonic** [comment] 2014-08-08 19:14
Hi there!  Sorry it's taken me so long to get back to you, I was out of town for two weeks and just finally got back to responding to these.

Your description of your wire connections seems a little off, but I might just be misreading it.  The wire from pin 20 on the drive should only be plugged into pin 2 on the Arduino for the first drive.  And a separate wire from the second drive's pin 20 should be plugged into pin 4 on the Arduino.  That is, pins 2 and 4 should not be electrically connected at all.

Otherwise it does certainly _sound_ like you have everything connected.

Clicking forward a few clicks and backward a few doesn't seem right though... if you have the DIR pin grounded (jumpered), it should only move in one direction.  And when you un-ground it should only move in the other direction.

**Comment by ten0rplaya04** [comment] 2014-08-08 22:20
No problem at all.  I had taken everything apart to work on a different project while I waited.

Put everything back together.  Redownloaded the zip of the project and started from scratch.  Decided to do a 1-drive setup to try and test using a Sony MPF920.  I'm still having the same sort of issue.

Pin 17 & pin 19 are connected to my breadboard (-) and then jumped from there to the GND on my Arduino. 
Pin 18 is connected to pin 3 on my Arduino.
Pin 20 is connected to pin 2 on my Arduino.

I've run with both flipped and 18/3 20/2 seems to be the one that gives the most movement.

Video: http://youtu.be/ivJ4qIy1H9A
Using Tetris included in samplesongs folder.

**Comment by samphonic** [comment] 2014-08-08 22:53
Alright the video was great because I can actually see what you're talking about with the weird movement.  Here's what I can tell you:

Everything is connected correctly.  Hooray!  It's moving enough, and forwards and backwards enough, that it's clear that the correct wires are hooked up, and that the MIDI is playing through the Arduino just fine.  So none of the wires are in the absolute wrong spots at least.

You clearly have pins 17 & 19 grounded to the Arduino (very clean breadboard set up you've got there, by the way), but I'm still suspecting grounding issues.  First thing to check is: are there actually pins at position 17 and 19 on the floppy drive itself?  And if there are, are they actually connected to ground (tougher to check, but if you have a multimeter you can check for continuity between these pins and the floppy casing or the black line on the power supply).

Something to try would be to take another wire connected to the (-) on your breadboard and touch it to the floppy drive casing, or to a black line from the power supply that's powering the floppy drive.  Sometimes floppy drives are lazy with the way the odd pins are connected.

**Comment by samphonic** [comment] 2014-08-08 22:58
Other crazy things to try:
- I notice you're using a laptop-- try plugging it into AC power (as opposed to using battery power)
- Try one of the GND pins on the other side of the Arduino.  I can't imagine why this would make a difference, but I've only ever used the GND on the Power side.

Edit: _DEFINITELY DON'T_ also try powering the Arduino from the same power supply that's powering the floppy drive.

**Comment by ten0rplaya04** [comment] 2014-08-08 23:26
I will try the grounding thing when I get home tonight. I don't have a multimeter yet, though it's on my list of things to buy next month.  I'll see if I can bum one.

The floppy drive has all the pins except pin 4. I have some samsung drives that are missing the ground pins so I haven't tried to use them yet.

The floppy drive is connected to a 200w psu. The laptop supplies the arduino with power and the psu supplies the floppy. I may try grounding the floppy pins to the psu and see if that resolves the issue as well.

**Comment by nimaid** [comment] 2014-08-08 23:33
DO NOT PLUG TWO POWER SOURCES INTO YOUR ARDUINO! If you plug the power supply to the Vin and ground, then also plug the USB into your computer, it's almost exactly the same as plugging the 5v and ground lines into your computer USB. I'm not sure how your computer would react, but that sounds risky. 

Grounding is the way to go. If that doesn't work, maybe try decoupling.

**Comment by samphonic** [comment] 2014-08-08 23:39
Heh, so what @nimaid said then.  Don't do that.  =P

Grounding the floppy pins to the power supply won't do anything because they are ostensibly already grounded to the power supply.  The issue is that when the Arduino sets one of its pins to "LOW", it's setting it to its interpretation of 0v, and that 0v needs to be sufficiently close to the floppy drive's understanding of 0v for the signal to be picked up.  (I'm sure there're some nuances I'm missing there, but I think that's fairly accurate.

**Comment by ten0rplaya04** [comment] 2014-08-09 02:24
Test #1: Switching GND pins on Arduino
Same result as on the other GND pin. Tested on both GND pins next to power.

Test #2: Touching floppy drive casing with GND
Issue still present/No change

Still asking around for the multimeter.  I'm going to hook up a couple of other drives in this 1-drive config and find out if I can get it to work.  Any suggestions on hooking up the samsungs with their GND pins hacked off?  Only GND pins showing on them are 1, 11, 21,29, and 33.

**Comment by samphonic** [comment] 2014-08-09 03:11
Weird that it's still not working... Theoretically all the GND pins on the floppies should be common anyway, so you could hook up to any of the available ones, or to the power supply ground.

**Comment by samphonic** [comment] 2015-02-18 23:57
Closing due to lack to activity.

**Closed as completed by samphonic** 2015-02-18 23:57 UTC
